### ISSUE TITLE
Memory pressure link is 404

### ISSUE THREAD

**Issue by aj2s** [leandromoreira/linux-network-performance-parameters#12]
https://github.com/leandromoreira/linux-network-performance-parameters/blob/4f2109dfdd7dfc3cece0a516877fbb63f4f0aac1/README.md?plain=1#L156

https://wwwx.cs.unc.edu/~sparkst/howto/network_tuning.php returns 404 for me

**Comment by leandromoreira** [comment]
Thank you!
