### ISSUE TITLE
how do you make the picture?which software?

### ISSUE THREAD

**Issue by mrnixe** [leandromoreira/linux-network-performance-parameters#3]
hello~
can you tell me  how do you generate the picture in the "readme" file?
thx

**Comment by leandromoreira** [comment]
Hello @mrnixe I think I used https://www.draw.io/ or any other online drawing workflow. I don't have skills with desktop drawing tools anymore 💣 the last time I had was with MSPaint 🎨

**Comment by mrnixe** [comment]
Thank you for your answer~ @leandromoreira
